site_name: PyPOSIX
theme:
  name: ivory

nav:
    - Home: index.md
    - Template: template.md
    - Cryptographic Services: Cryptographic_Services/index.md


markdown_extensions: 
    - fenced_code

